services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
      - redis_config:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: redis
      REDIS_PORT: 6379
      REDIS_DATABASES: 16

volumes:
  redis_data:
    driver: local
  redis_config:
    driver: local